name: GT People
type: Site
description: Drupal recipe for the GT People content type

install:
  - address
  - geocoder
  - geofield
  - geofield_map
  - pathauto
  - telephone
  - twig_tweak

config:
  import:
    address: '*'
    geocoder: '*'
    geofield: '*'
    pathauto: '*'
    telephone: '*'
